apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zzpy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-zzpy@sha256:4644bf3949201db3fa14b1c69bf295a8390d8ea56a87498102c15081cab22ea4
        name: my-nodejs
        resources: {}
status: {}
